### PR TITLE
Autofocus support

### PR DESCRIPTION
**Pull request by nxtpl**
Autofocus was not working, the fix resolves this problem.

### CODE REVIEW

**Review by LeaVerou — CHANGES_REQUESTED** [review]
Hey, thanks for this fix!!

Why duplicate the appendChild instead of just:

```js
if (ref.getAttribute("autofocus") != null) {
	ref.focus();
}
```
?

**Comment by nxtpl** [comment]
Good point, I will submit new PR in a moment :)

**Comment by nxtpl** [comment]
Updated the code

**Comment by LeaVerou** [comment]
LGTM, merged, thanks!

**Pull request merged**
