### PR TITLE
Fix for #17113

### PR DESCRIPTION
**Pull request by stephenkeable**
Added html hidden attributes to status element, on close and remove on
open.
Tested with Apple VoiceOver on Mac OS and status is still spoken
allowed.

### CODE REVIEW

**Comment by LeaVerou** [comment]
Thanks for working on this!
Not sure how there are conflicts, since this is a fresh PR. 
It does look like there is a bunch of other changes though as well, could you take a look at the diff? Is that normal?

**Comment by stephenkeable** [comment]
Forgot to merge the current branch into mine before making changes, rookie error.

**Comment by LeaVerou** [comment]
Much better, thanks! 
I don't understand though, why apply `hidden` to it instead of removing it from the DOM and re-adding it on `open()`?

**Comment by stephenkeable** [comment]
There is an instruction "Type x or more characters for results." given to user/screen reader, before open() is fired. 
Also matching the behaviour of the `<ul>` which is hidden, but left within the DOM.

**Comment by LeaVerou** [comment]
Ah ok. Merged, thanks!

**Pull request merged**
