### PR TITLE
Karma test runner

### PR DESCRIPTION
**Pull request by vlazar**
Replaces plain Jasmine spec runner with [Karma](http://karma-runner.github.io/) test runner.

Karma test runner is a much more convenient way to run tests. It allows to run tests in multiple browsers locally or in the cloud, shows failures in console, provides debugger, can be used with Continuous Integration server as Travis CI, and so on and so forth.

### CODE REVIEW

**Comment by vlazar** [comment]
Have you had a chance to check it out? It's easy (provided you already have Chrome and node.js installed):

```
git clone https://github.com/vlazar/awesomplete.git
git checkout features/karma-runner
npm install
npm test
```

Meanwhile... I'm gradually adding more Jasmine specs and using Karma runner.

**Teaser:**

```
Chrome 42.0.2311 (Mac OS X 10.9.5): Executed 64 of 66 (skipped 2) SUCCESS (0.129 secs / 0.103 secs)
```

That's right, ~0.1 secs to run all the tests. Instant feedback!

**Comment by vlazar** [comment]
@LeaVerou I'm close to having almost full test coverage for Awesomplete in Jasmine soon. After it's done I plan to review tests and do some cleanup before doing PR for review on how easy Jasmine tests are.

Tests are already quite useful. Some bugs were uncovered and I have some ideas about possible API tweaks. Running the whole test suite with Karma sill takes less than 1 second, so it would help a lot in quick and safe bug fixing or refactoring.

**Comment by LeaVerou** [comment]
I have no time to review this properly, but since it's separate and you seem willing to work on it, I’m merging it anyway. Thanks so much!

**Comment by vlazar** [comment]
Thanks Lea! Yes, I will definitely continue my work on it.

One way to make it easier for you as well as others is to setup a Travis CI, so that tests will be executed on each pit push and results will be visible on github very quickly (doesn't mean no PR review necessary, but at least changes with test failures are most likely not ready for merge).

Will do a separate PR for Travis CI.

**Comment by vlazar** [comment]
@LeaVerou PR for running tests on Travis CI #16753. This way you can get feedback when someone adds tests or changes code.

**Pull request merged**
