### PR TITLE
Add aria-controls attribute to input element

### PR DESCRIPTION
**Pull request by weeblr**
Currently using aria-owns attribute to relate input and listbox, per ARIA 1.0. Added use of aria-controls, per ARIA 1.1. 
Left aria-owns in place for B/C and also makes sense as list is a sibling of input anyway.

### CODE REVIEW

**Review by LeaVerou — APPROVED** [review]
Thank you!

**Comment by weeblr** [comment]
@LeaVerou Thanks for merging!

Will this be in an update to the npm package or is it only distributed through https://projects.verou.me/awesomplete/?

**Comment by LeaVerou** [comment]
I guess I should publish it, it's been a long time!

**Comment by weeblr** [comment]
That'd be great, thank you!

**Comment by LeaVerou** [comment]
Done!

Wow this package has some old stuff. `bower.json` lol, blast from the past 🤣

**Comment by weeblr** [comment]
Thanks for taking the time to update the package, it'll be useful!

**Pull request merged**
