### PR TITLE
Update README with bower installation instructions

### PR DESCRIPTION
**Pull request by iamnewton**

### CODE REVIEW

**Comment by LeaVerou** [comment]
Um, there’s something wrong with your editor. Check out the diff…

**Comment by iamnewton** [comment]
Yeah, when I opened the file the line-endings in the file were coming up as CRLF, so I unixed the file.  I can revert and commit as CRLF. Or try and figure out why ViM is playing with the line-endings.

**Comment by iamnewton** [comment]
There reverted my change and updated it.  Probably poofed that change, haha.  Let me know, and I can always redo.

**Comment by LeaVerou** [comment]
This is very weird. The line endings really shouldn’t be CRLF, and there’s no reason for them to be CRLF :-S 
Also, I can’t merge this PR due to merge conflicts now, and I would _really_ prefer a diff that doesn’t change the line endings so I can properly review the diff. Right now for some reason it seems that it’s making HUGE changes in the code, that I’m pretty sure you didn’t intend.

**Comment by iamnewton** [comment]
Yeah. I'll start over I guess. Sorry about that.

**Comment by LeaVerou** [comment]
No need to be sorry, thanks for contributing!

**Comment by LeaVerou** [comment]
Closing this PR then :)

**Pull request closed without merging**
