### PR TITLE
Fix undefined error in evaluate function

### PR DESCRIPTION
**Pull request by vleontyev**
Fix issue #17124

### CODE REVIEW

**Comment by LeaVerou** [comment]
Hey, thanks! You can just do `this._list && this._list.length > 0` and that should fix the issue more succinctly.
Can you change it?

**Comment by vleontyev** [comment]
done

**Comment by vleontyev** [comment]
@LeaVerou do you have an estimate when are you going to merge it into main branch?

**Comment by LeaVerou** [comment]
Oops, I forgot about this! Merged now, thanks for fixing it! (and for your patience!)

**Pull request merged**
