### PR TITLE
[BUGFIX] Keydown evts when `ul` hidden shouldn't trigger component handling

### PR DESCRIPTION
**Pull request by alexdiliberto**
This fixes a bug where previously, if the `ul` was hidden, the component would still act upon keydown events for Enter/Esc/Up/Down

To replicate the previous bug: In the demo, you can select `Java` then keyup and down. You know see that the context is not within the input tag iself, however it's within the component which is still selecting items from the previously searched list.

As an aside, it was not apparent what method you were using to minify JS so I just compressed with my own approach.

### CODE REVIEW

**Comment by LeaVerou** [comment]
Thanks! Could you please use a getter e.g. `opened` that checks of the popup is open by returning `this.ul && this.ul.hasAttribute("hidden")`? Then you can just check for `me.opened` and other places in the code can use that condition instead of repeating it (same with scripts using the code).

**Comment by alexdiliberto** [comment]
@LeaVerou Sure thing. Added it https://github.com/alexdiliberto/awesomplete/commit/db991e1817f90d7bd5cf2ca1b25d4f4229335bd0

**Comment by LeaVerou** [comment]
Lovely. Now if you could only merge conflicts? Sorry for the delay!

**Comment by alexdiliberto** [comment]
@LeaVerou done

**Comment by LeaVerou** [comment]
Merged, thanks!

This is very minor, but in the future, could you please follow the coding style of the project? (e.g. space after `if`)

**Pull request merged**
