### PR TITLE
Feature: Sourcemaps

### PR DESCRIPTION
**Pull request by marcobiedermann**
Add `gulp-sourcemaps` to create a CSS sourcemap.
This might be helpful for debugging.
Unfortunately `gulp-closure-compiler-service` does not support the usage of sourcemaps.
Maybe you could switch to [gulp-uglify](https://www.npmjs.com/package/gulp-uglify) which does support it and is more active in development.
Using `gulp-uglify` is a bit less efficient (35 bytes) but I think it is worth it to support sourcemaps.
What do you think Lea?

### CODE REVIEW

**Comment by LeaVerou** [comment]
Sure, but you'd have to make that change too then :)

Thanks!

**Comment by marcobiedermann** [comment]
@LeaVerou Done!

To sum it up:
- add Sourcemaps for CSS and JavaScript files
- replace `gulp-closure-compiler-service` with `gulp-uglify`

**Comment by LeaVerou** [comment]
Awesome, thanks!!

**Comment by marcobiedermann** [comment]
@LeaVerou You are very welcome. I have to thank you for this awesome library 😄 🎉

**Pull request merged**
