### PR TITLE
Extract CONTRIBUTING.md to utilize a new GitHub feature

### PR DESCRIPTION
**Pull request by vlazar**
Setting guidelines for repository contributors
https://help.github.com/articles/setting-guidelines-for-repository-contributors/

> To help your project contributors do good work, you can add a file with contribution guidelines to the root of your project's repository. Then, whenever someone opens a pull request or creates an issue, they will see a link to that file.

### CODE REVIEW

**Comment by vlazar** [comment]
There are also [Issue and Pull Request templates](https://github.com/blog/2111-issue-and-pull-request-templates) which we can use to guide contributors.

Maybe you can add ISSUE_TEMPLATE.md and PULL_REQUEST_TEMPLATE.md? I'm not sure if you want it and what to put in those files.

**Comment by LeaVerou** [comment]
Nice, thanks!
I usually also put stuff that many contributors miss in there, or important facts about the codebase that they need to know, e.g. check this one: https://github.com/LeaVerou/dpi/blob/gh-pages/CONTRIBUTING.md
Are there any such things for Awesomplete?

**Comment by LeaVerou** [comment]
Btw, just saw your commit message. CONTRIBUTING.md is not a new Github feature. It existed for ages. The other two are new, and the possibility to put them all in a .github folder is also new.

**Comment by vlazar** [comment]
Oh, thanks! I didn't knew GitHub was showing a link to CONTRIBUTING file for ages.

> I usually also put stuff that many contributors miss in there, or important facts about the codebase that they need to know, e.g. check this one: https://github.com/LeaVerou/dpi/blob/gh-pages/CONTRIBUTING.md
> Are there any such things for Awesomplete?

I'll try to come up with something maybe shorter and more essential for CONTRIBUTING.md. It needs cleanup.

I must say I would also prefer a shorter README.md, since it's mostly a copy paste of docs part. Something closer to https://github.com/LeaVerou/dpi :)

**Pull request merged**
