### PR TITLE
Split styles into a less opinionated base stylesheet and a theme stylesheet and merge with Gulp

### PR DESCRIPTION
**Pull request by rikschennink**
CSS changes:
1. Reduced styling in base stylesheet to the bare minimum
2. Scoped the `[hidden]` and `.visually-hidden` selectors to prevent collisions
3. Removed `div` tag from selectors to lower specificity in order to make overriding easier
4. Added `#fff` background color to `ul` so results are readable without styles

I'm not a pro at pull requests so if I'm missing anything or doing anything out of the ordinary please let me know :-)

### CODE REVIEW

**Comment by LeaVerou** [comment]
Looks great, thanks!
Could you please add a note to CONTRIBUTING.md about this? Otherwise people will miss that `awesomplete.css` is generated and will send PRs that modify it (speaking from experience...)

**Comment by rikschennink** [comment]
Awesome ;-) 

And done!

**Comment by LeaVerou** [comment]
Thanks!

**Comment by rikschennink** [comment]
Fantastic! Thank you for building it in the first place :-)

**Pull request merged**
