### PR TITLE
Jasmine simple testing

### PR DESCRIPTION
**Pull request by juanto121**
Sample for awesomplete test using Jasmine. 
Didn't receive feedback on #14565 so I decided to PR. What do you think?

### CODE REVIEW

**Comment by juanto121** [comment]
Hi @LeaVerou , I know you must be really busy but any input on the matter would be much appreciated. Maybe Im missing something obvious?

**Comment by LeaVerou** [comment]
Oh my, it’s been 8 days already since this? So sorry!!

As someone who has never really used Jasmine, I have no idea how to write a test based on the sample code. I could of course go RTFM but I guess contributors will also have the same issue. Perhaps you could add a little quick intro on that? (perhaps in the README?)

**Comment by juanto121** [comment]
Ok, I'll work on it.

**Comment by LeaVerou** [comment]
Hey @juanto121, I went ahead and merged it anyway. Thanks for the work! But it would be nice if you could add some short documentation (referring to the original Jasmine docs where necessary). Also, could you please rename SpecRunner.html to index.html so that people don't have to type a filename as well?

**Comment by vlazar** [comment]
@LeaVerou Did you compared real world examples of tests in Jasmine vs QUnit or just 1 small test which tests that true is true? The difference in later case is not so obvious I think.

**Pull request merged**
