### PR TITLE
Tests for Awesomplete.ITEM and Awesomplete.REPLACE

### PR DESCRIPTION
**Pull request by vlazar**

### CODE REVIEW

**Comment by LeaVerou** [comment]
Thanks! Btw you don't need to send PRs and merge them yourself for things like that, just commit directly :)

**Comment by vlazar** [comment]
Sure, but doing PR also goes via TravisCI and Code Climate. Might also go via Sauce Labs cross browser testing one day. So it's safer :)

**Comment by LeaVerou** [comment]
Ah, I see. Ok then! :)

**Comment by vlazar** [comment]
Just realized, maybe you wanted less GitHub notifications noise. I'll keep this in mind then.

**Pull request merged**
