### PR TITLE
Allow for tab-completion, if not autoFirst and not shift+tab

### PR DESCRIPTION
**Pull request by fractaledmind**
A fixed version of #16833.

### CODE REVIEW

**Comment by LeaVerou** [comment]
LGTM. @vlazar, thoughts?

**Comment by vlazar** [comment]
Sorry @LeaVerou, a bit busy now to carefully think about it. Some thoughts though. More on original #16833 and expected behavior.

If I understood correctly, the  idea was to be able to select currently highlighted item by `Tab` key. So that instead of pressing `Enter` and then `Tab` you only need to press `Tab`.

So if `Tab` now selects an item and goes to next filed, why shouldn't `Shift+Tab` do the similar: select an item and go to previous field?

I'm also curious, if the behavior in this PR would be expected by default by all users. Any demos for autocomplete controls behaving in similar way?

Also, the check for `autoFirst` option disables tab completion. Won't this confuse people?

**Comment by vlazar** [comment]
Code itself looks good, but no tests :( With 3 new branches there should up to 8 new tests ;)

In case of LGTM for behavior on this PR I can help with tests.

**Comment by Nepherim** [comment]
@vlazar:jQuery UI uses tab to select, also shift-tab selects. https://jqueryui.com/autocomplete/

**Comment by vlazar** [comment]
Thanks @Nepherim! So in JQuery UI `Tab` and `Shift+Tab` at least work consistently.

Also, the `autoFocus` option does not change the tab behavior. See http://jsfiddle.net/Bqujj/

**Pull request closed without merging**
