### PR TITLE
Add ability to add custom aria-label to the autocomplete listbox and …

### PR DESCRIPTION
**Pull request by heatherpekrul**
…default verbiage to fix issue #17200, add documentation to readme regarding options

### CODE REVIEW

**Comment by heatherpekrul** [comment]
Travis is failing and this is what I see in the logs:

> ```
> 0.00s$ sh -e /etc/init.d/xvfb start
> sh: 0: Can't open /etc/init.d/xvfb
> The command "sh -e /etc/init.d/xvfb start" failed and exited with 127 during .
> Your build has been stopped.
> ```

Running `npm test` comes back clean so I'm not sure what's going on. I'm happy to amend the PR if you can point me in the right direction.

**Comment by LeaVerou** [comment]
Hi there,

Thank you for contributing!
I have no idea what's wrong with Travis, but I see nothing wrong with your code. 
The website is the canonical source of documentation, not the README. While I do appreciate you adding that table to the readme, could you please update the website as well?

Thank you!

**Comment by heatherpekrul** [comment]
Thanks for taking a look, @LeaVerou ! I've updated the website as well.

**Comment by LeaVerou** [comment]
Hey, sorry for the delay! There are conflicts now, could you resolve them? Thanks!

**Comment by heatherpekrul** [comment]
@LeaVerou : No worries! I've fixed the conflict.

**Comment by heatherpekrul** [comment]
@LeaVerou : Just checking in about this PR - is there anything else you'd like me to modify, change, or remove? I'm happy to amend this if there is. We use Awesomplete on a web property that we try to have a high degree of accessibility on, and this missing attribute came up on our report again and I realized I needed to check in.

Thank you!

**Comment by LeaVerou** [comment]
So sorry for the delay. Looks good to me now, sadly now there are conflicts again. Could you please rebase once more? Thanks!!

**Comment by heatherpekrul** [comment]
@LeaVerou It's a busy time, I understand. :) I've got the PR updated again. Please let me know if there's anything else you need from me.

**Comment by LeaVerou** [comment]
Did you push? It still reports conflicts.

**Comment by heatherpekrul** [comment]
I did push it up - I'm sorry, I must be looking in the wrong place. I see a message that says "This branch has no conflicts with the base branch" so somehow I'm not seeing where the problem is. Can you point me in the right direction? Thank you.

**Comment by LeaVerou** [comment]
Did you push to the `aria-listbox-label-issue-17200` branch?
This is what I see here:

image

**Comment by heatherpekrul** [comment]
@LeaVerou Sorry for the trouble, Lea. I rebased again and got a successful message, so hopefully it's okay now. I fixed two conflicts in README.md and index.html. I pushed it up and I see it in the commits. Fingers crossed... hard to double check when Github is still showing the green light about no conflicts here on the PR :)

**Comment by LeaVerou** [comment]
I still get the exact same message over here. 😢  Do you get a different one?

**Comment by heatherpekrul** [comment]
Really not sure what is going awry on my end... I followed the rebase instructions here closely (but with this repo):
https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

and I got this message:
Successfully rebased and updated refs/heads/aria-listbox-label-issue-17200

Then I pushed it up, and I see the resulting push here. I see a Github message here that says "This branch has no conflicts with the base branch" - I don't see any errors or conflicts. Hopefully this is good now?

Very sorry about the trouble. Thank you for your patience with me - I haven't contributed to very many open source projects.

**Comment by LeaVerou** [comment]
Now it worked! Merged, thanks!

**Comment by heatherpekrul** [comment]
Thank you so much!

**Pull request merged**
