### PR TITLE
Replace make with gulp

### PR DESCRIPTION
**Pull request by vlazar**
Replaces minification via Makefile added in #14475 with minification via gulp.

There was an issue with minification via Makefile reported in #16773. Most likely a different shell behavior.

@LeaVerou Since you use gulp on other project, I think it's reasonable to replace make with gulp. It would be useful for other automation stuff too.

### CODE REVIEW

**Comment by LeaVerou** [comment]
Awesome, thanks! Yes, I use gulp everywhere now, so this is very appreciated :)

**Comment by LeaVerou** [comment]
Btw, @vlazar, I noticed you had several merged PRs, so I made you a collaborator (commit access, admin rights on issues & PRs) :)
Thank you so much for your contributions!

Please still send PRs for non-minor core changes.

**Comment by vlazar** [comment]
Thank you for you trust, @LeaVerou. I promise not to abuse collaborator access :)

Still I feel like sending PRs instead of direct commits is a best way most of the time. Maybe I miss some use case.

Anyway. I'll probably will send and merge some of my PRs (like tests related stuff) by myself.

Changes for anything other than that will wait in PRs for your review. I'm not comfortable changing the code how I want on your behalf. Most of the time any change needs a discussion, so I'll open an issue or PR anyway.

**Comment by LeaVerou** [comment]
Thanks, that makes sense!
Yes, feel free to merge in any test-related stuff without asking me. Also, minor changes to the core code are fine. I think you have a good grasp on when it's ok to commit directly and what needs a PR :) Welcome!

**Pull request merged**
