### PR TITLE
Up version of bower.json and package.json to 0.1.0 in order to npm an…

### PR DESCRIPTION
**Pull request by rbecheras**
Up version of bower.json and package.json to 0.1.0 in order to npm and bower publish.

If you merge, you should also create a tag v0.1.0 as in my fork: https://github.com/rbecheras/awesomplete/releases (tags can't be part of pull requests, you have to make it yourself in the main repo).

That will fix #25

### CODE REVIEW

**Comment by rbecheras** [comment]
I registred my repo into the public bower registry as rbecheras-awesomplete after tagged the v0.1.0 release tag.

Now, you all can use it to install it via bower : 

```
$ bower install rbecheras-awesomplete
bower rbecheras-awesomplete#*   cached git://github.com/rbecheras/awesomplete.git#0.1.0
bower rbecheras-awesomplete#* validate 0.1.0 against git://github.com/rbecheras/awesomplete.git#*
bower rbecheras-awesomplete#~0.1.0          install rbecheras-awesomplete#0.1.0
```

@LeaVerou, please let me know if you need help to do it and/or when you did it. Then, I'll remove my own temporary package.

**Comment by rbecheras** [comment]
also fix #786 (referencing issues)

**Comment by rbecheras** [comment]
@LeaVerou Maybe you would want to add me as collaborator for your repository, that will make me write rights. 
I'd can reorganise your branches (split gh-pages and master) and package for bower and npm registrations.
As you want, I am available.

**Comment by erquhart** [comment]
:+1:

**Comment by LeaVerou** [comment]
Oops, I made a 1.0.0 release before seeing this! Could you update? Thanks!

**Comment by rbecheras** [comment]
@LeaVerou , could you grant me write access to the repo ?

**Comment by LeaVerou** [comment]
Sorry @rbecheras, just saw this. :( No idea how I missed it :(
Are you still interested?

**Comment by vlazar** [comment]
Removed version in bower.json #16863

We will release 1.1 soon. Track progress here https://github.com/LeaVerou/awesomplete/milestones/v1.1

**Pull request closed without merging**
